import { writeFile } from "node:fs/promises";
import { stringify as toYaml } from "yaml";
import { consola } from "consola";
import type { AnnotationMap, FieldAnnotation } from "@chameleon/core";
import {
  parseOpenAPI,
  parseGraphQL,
  parsePostman,
  parsePact,
  inferAnnotation,
} from "@chameleon/core";

interface AnnotateOptions {
  output?: string;
  type?: "openapi" | "graphql" | "postman" | "pact";
}

/**
 * Generates a starter annotations YAML file from a schema.
 * All fields are listed with their inferred faker mappings.
 * Users can then override any field.
 */
export async function runAnnotate(schemaPath: string, options: AnnotateOptions): Promise<void> {
  const type = options.type ?? detectType(schemaPath);
  consola.start(`Generating annotations from ${type} schema: ${schemaPath}`);

  let routes;
  try {
    switch (type) {
      case "openapi":
        routes = await parseOpenAPI(schemaPath);
        break;
      case "graphql":
        routes = await parseGraphQL(schemaPath);
        break;
      case "postman":
        routes = await parsePostman(schemaPath);
        break;
      case "pact":
        routes = await parsePact(schemaPath);
        break;
      default:
        routes = await parseOpenAPI(schemaPath);
    }
  } catch (err) {
    consola.error(`Failed to parse schema: ${String(err)}`);
    process.exit(1);
  }

  const annotations: AnnotationMap = { version: 1, paths: {}, graphql: { types: {} } };

  for (const route of routes) {
    if (route.source === "graphql") continue;

    const pathKey = route.path;
    const methodKey = route.method.toLowerCase();

    if (!annotations.paths![pathKey]) {
      annotations.paths![pathKey] = {};
    }

    const response: Record<string, FieldAnnotation> = {};

    for (const field of route.responses[0]?.fields ?? []) {
      if (field.type === "object" || field.type === "array") continue;

      const inferred = inferAnnotation(field);
      if (inferred) {
        response[field.path] = inferred;
      }
    }

    annotations.paths![pathKey]![methodKey] = { response };
  }

  const yaml = [
    "# Generated by: chameleon annotate",
    "# Edit this file to customize fake data generation.",
    "# Docs: https://github.com/EmanueleMinotto/chameleon#annotations",
    "",
    toYaml(annotations, { lineWidth: 100 }),
  ].join("\n");

  const outputPath = options.output ?? "./chameleon/annotations/generated.annotations.yml";

  if (options.output === "-") {
    process.stdout.write(yaml);
  } else {
    await writeFile(outputPath, yaml, "utf-8");
    consola.success(`Annotations written to ${outputPath}`);
  }
}

function detectType(path: string): "openapi" | "graphql" | "postman" | "pact" {
  const lower = path.toLowerCase();
  if (lower.endsWith(".graphql") || lower.endsWith(".gql")) return "graphql";
  if (lower.includes("postman") || lower.includes("collection")) return "postman";
  if (lower.includes("pact")) return "pact";
  return "openapi";
}
