import type { Context } from "hono";
import type { ChameleonRoute } from "@chameleon/core";
import { randomUUID } from "node:crypto";

// ── Hoppscotch collection ──────────────────────────────────────────────────────

function buildHoppscotchCollection(routes: ChameleonRoute[], baseUrl: string, title: string) {
  const restRoutes = routes.filter((r) => r.source !== "graphql");
  return {
    v: 1,
    name: title,
    folders: [],
    requests: restRoutes.map((route) => ({
      v: "1",
      id: randomUUID(),
      name: `${route.method} ${route.path}`,
      method: route.method,
      endpoint: `${baseUrl}${route.path}`,
      headers: [],
      params: [],
      body: { contentType: null, body: null },
      auth: { authType: "none", authActive: false },
      requestVariables: [],
    })),
  };
}

// ── Postman collection (v2.1) ──────────────────────────────────────────────────

function buildPostmanCollection(routes: ChameleonRoute[], baseUrl: string, title: string) {
  const restRoutes = routes.filter((r) => r.source !== "graphql");
  return {
    info: {
      name: title,
      _postman_id: randomUUID(),
      schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
      description: "Generated by Chameleon",
    },
    item: restRoutes.map((route) => {
      const segments = route.path.split("/").filter(Boolean);
      const pathSegments = segments.map((s) => (s.startsWith("{") ? `:${s.slice(1, -1)}` : s));
      const pathVars = segments
        .filter((s) => s.startsWith("{"))
        .map((s) => ({ key: s.slice(1, -1), value: "" }));
      const url: Record<string, unknown> = {
        raw: `{{baseUrl}}${route.path}`,
        host: ["{{baseUrl}}"],
        path: pathSegments,
      };
      if (pathVars.length) url["variable"] = pathVars;
      return {
        name: `${route.method} ${route.path}`,
        request: { method: route.method, header: [], url },
        response: [],
      };
    }),
    variable: [{ key: "baseUrl", value: baseUrl, type: "string" }],
  };
}

// ── Landing page ───────────────────────────────────────────────────────────────

function buildHtml(
  title: string,
  explorerPath: string,
  routes: ChameleonRoute[],
  collectionUrl: string,
): string {
  const restRoutes = routes.filter((r) => r.source !== "graphql");
  const rows = restRoutes
    .map(
      (r) =>
        `<tr><td class="method ${r.method.toLowerCase()}">${r.method}</td><td>${r.path}</td></tr>`,
    )
    .join("\n");

  const hoppImportUrl = `https://hoppscotch.io/#/?url=${encodeURIComponent(collectionUrl)}`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, sans-serif; background: #0f172a; color: #e2e8f0; min-height: 100vh; padding: 2rem; }
    .container { max-width: 800px; margin: 0 auto; }
    h1 { font-size: 1.75rem; font-weight: 700; margin-bottom: 0.25rem; }
    .subtitle { color: #94a3b8; margin-bottom: 2rem; font-size: 0.95rem; }
    .card { background: #1e293b; border-radius: 0.75rem; padding: 1.5rem; margin-bottom: 1.5rem; }
    h2 { font-size: 1rem; font-weight: 600; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 1rem; }
    .actions { display: flex; gap: 0.75rem; flex-wrap: wrap; }
    a.btn { display: inline-flex; align-items: center; gap: 0.5rem; padding: 0.6rem 1.2rem; border-radius: 0.5rem; text-decoration: none; font-weight: 500; font-size: 0.9rem; transition: opacity 0.15s; }
    a.btn:hover { opacity: 0.85; }
    .btn-primary { background: #6366f1; color: #fff; }
    .btn-secondary { background: #334155; color: #e2e8f0; }
    .note { margin-top: 0.75rem; font-size: 0.8rem; color: #64748b; }
    table { width: 100%; border-collapse: collapse; }
    th { text-align: left; color: #64748b; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; padding-bottom: 0.5rem; border-bottom: 1px solid #334155; }
    td { padding: 0.6rem 0; border-bottom: 1px solid #1e293b; font-size: 0.9rem; }
    td.method { font-family: monospace; font-weight: 600; width: 80px; }
    .get { color: #34d399; } .post { color: #60a5fa; } .put { color: #fbbf24; }
    .patch { color: #f97316; } .delete { color: #f87171; } .head, .options { color: #a78bfa; }
  </style>
</head>
<body>
  <div class="container">
    <h1>${title}</h1>
    <p class="subtitle">Powered by Chameleon — import the collection into your API client to start testing.</p>

    <div class="card">
      <h2>Hoppscotch</h2>
      <div class="actions">
        <a class="btn btn-primary" href="${hoppImportUrl}" target="_blank" rel="noopener">Open in Hoppscotch</a>
        <a class="btn btn-secondary" href="${explorerPath}/collection.json" download="collection.json">Download collection.json</a>
      </div>
    </div>

    <div class="card">
      <h2>Postman</h2>
      <div class="actions">
        <a class="btn btn-secondary" href="${explorerPath}/postman.json" download="postman.json">Download postman.json</a>
      </div>
    </div>

    <div class="card">
      <h2>Bruno</h2>
      <div class="actions">
        <a class="btn btn-secondary" href="${explorerPath}/postman.json" download="postman.json">Download postman.json</a>
      </div>
      <p class="note">Bruno supports Postman Collection v2.1 import — use the file above.</p>
    </div>

    <div class="card">
      <h2>Available routes (${restRoutes.length})</h2>
      <table>
        <thead><tr><th>Method</th><th>Path</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </div>
  </div>
</body>
</html>`;
}

// ── Handlers ───────────────────────────────────────────────────────────────────

export function handleExplorerPage(
  c: Context,
  routes: ChameleonRoute[],
  title: string,
  explorerPath: string,
): Response {
  const origin = new URL(c.req.url).origin;
  const collectionUrl = `${origin}${explorerPath}/collection.json`;
  const html = buildHtml(title, explorerPath, routes, collectionUrl);
  return c.html(html);
}

export function handleHoppscotchCollection(
  c: Context,
  routes: ChameleonRoute[],
  title: string,
  baseUrl: string,
): Response {
  const collection = buildHoppscotchCollection(routes, baseUrl, title);
  return c.json(collection);
}

export function handlePostmanCollection(
  c: Context,
  routes: ChameleonRoute[],
  title: string,
  baseUrl: string,
): Response {
  const collection = buildPostmanCollection(routes, baseUrl, title);
  return c.json(collection);
}
