/**
 * Vercel Entry Point — DO NOT MODIFY
 *
 * This file is the single serverless function that handles all requests.
 * It loads the pre-built manifest (generated by `chameleon build`) and
 * creates a Hono app that serves fake responses.
 *
 * The manifest is generated automatically by Vercel's buildCommand:
 *   "buildCommand": "pnpm chameleon build --config chameleon/chameleon.config.ts"
 *
 * To add routes or change behavior, edit:
 *   - chameleon/chameleon.config.ts  (configuration)
 *   - chameleon/schemas/            (API schemas)
 *   - chameleon/annotations/        (annotation files)
 *   - chameleon/generators/         (custom generator functions)
 */
import type { IncomingMessage, ServerResponse } from "node:http";
import type { Manifest } from "@chameleon/core";
import { createAppFromManifest } from "@chameleon/server";

// The manifest is built at deploy time by `chameleon build`
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — file is generated at build time
import manifest from "../.chameleon/manifest.json" with { type: "json" };

export const config = { runtime: "nodejs" };

const app = await createAppFromManifest(manifest as unknown as Manifest);

/**
 * Vercel Node.js runtime calls the default export with (IncomingMessage, ServerResponse).
 * Hono's app.fetch() expects a Web API Request, so we convert here.
 */
export default async function handler(req: IncomingMessage, res: ServerResponse) {
  const host = req.headers.host ?? "localhost";
  const url = new URL(req.url ?? "/", `http://${host}`);

  const headers = new Headers();
  for (const [key, val] of Object.entries(req.headers)) {
    if (val === undefined) continue;
    for (const v of Array.isArray(val) ? val : [val]) headers.append(key, v);
  }

  const method = req.method ?? "GET";
  const hasBody = method !== "GET" && method !== "HEAD";
  const body = hasBody
    ? await new Promise<Uint8Array>((resolve, reject) => {
        const chunks: Buffer[] = [];
        req.on("data", (chunk: Buffer) => chunks.push(chunk));
        req.on("end", () => resolve(Buffer.concat(chunks)));
        req.on("error", reject);
      })
    : undefined;

  const response = await app.fetch(new Request(url, { method, headers, body }));

  res.statusCode = response.status;
  response.headers.forEach((value, key) => res.setHeader(key, value));
  res.end(Buffer.from(await response.arrayBuffer()));
}
