/**
 * Vercel Entry Point — DO NOT MODIFY
 *
 * This file is the single serverless function that handles all requests.
 * It loads the pre-built manifest (generated by `chameleon build`) and
 * creates a Hono app that serves fake responses.
 *
 * The manifest is generated automatically by Vercel's buildCommand:
 *   "buildCommand": "pnpm chameleon build --config chameleon/chameleon.config.ts"
 *
 * To add routes or change behavior, edit:
 *   - chameleon/chameleon.config.ts  (configuration)
 *   - chameleon/schemas/            (API schemas)
 *   - chameleon/annotations/        (annotation files)
 *   - chameleon/generators/         (custom generator functions)
 */
import { handle } from "hono/vercel";
import { createAppFromManifest } from "@chameleon/server";

// The manifest is built at deploy time by `chameleon build`
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — file is generated at build time
import manifest from "../.chameleon/manifest.json" assert { type: "json" };

export const config = {
  runtime: "nodejs",
  // Switch to "edge" for faster cold starts (note: some custom generators may not work on Edge)
  // runtime: "edge",
};

// Create the Hono app from the manifest and export it as the Vercel handler
const app = await createAppFromManifest(manifest);
export default handle(app);
